# Generated by Django 4.1.1 on 2022-10-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
