# Generated by Django 4.1.1 on 2022-10-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetail',
            fields=[
                ('Student_name', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField(primary_key=b'I01\n', serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
